name: xscore
description: XScore - Xbox stats tracker
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  provider: ^6.1.2
  http: ^1.2.2
  url_launcher: ^6.3.0
  cached_network_image: ^3.4.1
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  system_theme: ^3.2.0
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true