name: xscore
description: "XScore - Xbox stats, achievements, friends & clips tracker"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  http: ^1.2.1
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
